
/*--------------------------------------------------------*/
/*   AUTHOR    	 : THENNARASU            	      	  */
/*   DATE 	 : 12-01-2019	        	      	  */
/*   DESCRIPTION : LEFT SHIFTING USED LSL	   	  */
/*   FILE_NAME	 : RIGHT_TO_LEFT_ADDITION.asm		  */
/*--------------------------------------------------------*/




			AREA RESET,CODE,READONLY
			ENTRY
PINSEL0			EQU	0XE002C00       ;PINSEL = ADDRESS
IO0DIR			EQU	0XE0028008      ;INPUT SELECTION 1 = OUTPUT  0 = INPUT 
IO0SET			EQU	0XE0028004      ;SET THE PIN THIS ADDRESS
IO0CLR			EQU	0XE002800C      ;CLEAR THE PINS
	
	
			LDR R0,=PINSEL0     	;PINSEL ADDRESS LOAD TO R0
			LDR R1,[R0]         	;R0-RGISTER HAVE SOME ADDRESS THAT ADDRESS STORE IN ONE VALUE THAT VALUE LOAD TO R1
			MOV R1,#0X00000000  	;MOV VALUE R1 REGISTER
			STR R1,[R0]         	;R1 VALUE STORE TO R0 ADDRESS
			
			LDR R0,=IO0DIR     	;IO0DIR ADDRESS LOAD TO R0 
			LDR R1,[R0]        	;R0 -REGISTER HAVE SOME ADDRESS THAT ADDRESS STORE IN ONE VALUE THAT VALUE LOAD TO R1
			MOV R1,#0XFFFFFFFF 	;MOVE VALUE R1 REGISTR
			STR R1,[R0]       	;R1 VALUE STORE TO R0 ADDRESS
LOOP
           		MOV R2,#1           	;MOVE VALUE R2 REGISTER
			MOV R3,#32
	

LOOP1			LDR R0,=IO0SET     	;IO0SET ADDRESS LOAD TO R0 
			LDR R1,[R0]         	;R0 -REGISTER HAVE SOME ADDRESS THAT ADDRESS STORE IN ONE VALUE THAT VALUE LOAD TO R1
			MOV R1,R2          	;MOVE R2 VALUE R1 REGISTR
			STR R1,[R0]       	;R1 VALUE STORE TO R0 ADDRESS
		
		
			LDR R0,=IO0CLR	        ;IO0CLR ADDRESS LOAD TO R0 
			LDR R1,[R0]     	;R0 -REGISTER HAVE SOME ADDRESS THAT ADDRESS STORE IN ONE VALUE THAT VALUE LOAD TO R1
			MOV R1,R2               ;MOVE R2 VALUE R1 REGISTR
			STR R1,[R0]             ;R1 VALUE STORE TO R0 ADDRESS
			LSL R2,#1           	;R2 REGISTER VALUE RIGHT TO LEFT SHIFT USING LSL INSTRUCTION
            		SUBS R3,#1          	;SUBTRACT THE R3  VALUE 1
			BNE LOOP1           	;WHEN ZER0 FLAG IS SET THAT EXIT
			B   LOOP            	;END OF THE LOOP BRANCH
			END			;END THE PROGRAM
