/*		ADDITION OF 8_BIT					*/
/*		AUTHOR	=> THENNARASU					*/
/*		DATE    => 14-10-2018					*/	


		AREA ADDITION1,CODE,READONLY
		ENTRY
		MOV R0,#0XFF	;MOVE VALUE TO R0 REGISTER
		MOV R1,#0XFF	;MOVE VALUE TO R1 REGISTER
		ADD R0,R1	;ADD THE VALUE REGISTER R0 AND R1 R0+=R1
	LOOP    B	LOOP    ;THE CONDITION OF LOOP  
		END		;END THE PROGRAM
