			AREA ZERO_BIT_SET_CPSR,CODE,READONLY
			ENTRY                           
			MOV R1,#0X00000000			;MOVE VALUE TO R1 REGISTER
			MOV R2,#0X00000000          		;MOVE VALUE T0 R2 REGISTER
			ADDS R1,R2				;WHEN WE ADD 'S' THAT TIME CPSR STATUS WILL BE UPDATED
			END					;END THE PROGARM
